# Discovery Server Access
eureka.client.healthcheck.enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.52.145:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: query-service

server:
  port: 1514